### ISSUE TITLE
Adicionar introdução ao RStudio

### ISSUE THREAD

**Issue by rmhirota** [beatrizmilz/2020-R-LadiesSP-DataViz#2]
Procurar de outras apresentações:
[Workshop R Básico](https://github.com/beatrizmilz/2020-R-Ladies-SP-Basico)

**Comment by beatrizmilz** [comment]
Sugestão da @hsvab: retirar essa seção. Colocaremos pré-requisito.

**Comment by beatrizmilz** [comment]
Retirado!
